name: fitness_tracker
description: A fitness tracking application

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  fl_chart: ^0.64.0
  intl: ^0.18.1
  flutter_local_notifications: ^16.1.0
  google_fit: ^2.1.1
  pedometer: ^3.0.1
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9